echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf datazets.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf datazets/__pycache__
rm -rf datazets/.pylint.d
rm -rf datazets/tests/__pycache__
rm -rf tests/__pycache__
rm -rf datazets/utils/__pycache__
rm -rf .pylint.d
rm -rf datazets/data/*.zip
rm -rf datazets/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf .coverage*
rm -rf .pkl
rm -rf datazets.egg-info